export interface CandidateProfile {
  id: string;
  fullName: string;
  email: string;
  phone: string;
  currentSituation: string; // e.g., "Étudiant en 3e année de B.U.T. Techniques de Commercialisation à l'IUT Clermont Auvergne, campus de Montluçon"
  currentAlternance: string; // e.g., "Crédit Agricole de Commentry"
  targetMasters: string[]; // e.g., ["Finance", "Fintech", "Gestion de patrimoine"]
  skills: string[];
  languages: string[];
  certifications: string[];
  projects: Array<{ id: string; title: string; description: string }>;
  experiences: Array<{ id: string; role: string; company: string; period: string; description: string }>;
  bio: string;
  profileCompletionScore: number; // 0 - 100
}

export type OpportunityStatus = 'saved' | 'to_prepare' | 'to_study' | 'to_apply';

export interface RecruiterContact {
  name?: string;
  role?: string;
  email?: string;
  phone?: string;
  linkedin?: string;
  linkedinUrl?: string;
}

export interface EnterpriseDetails {
  presentation?: string;
  parentGroup?: string;
  secteur?: string;
  taille?: string;
  siege?: string;
  chiffresCles?: Array<{ label: string; value: string }>;
  faitsMarquants?: string[];
  partenairesClients?: string[];
}

export interface WorkflowStepItem {
  step: number; // 1 to 9
  id: string;
  title: string;
  desc: string;
  status: 'completed' | 'current' | 'upcoming';
  date?: string;
  notes?: string;
}

export interface ExtractedJobInfo {
  missions: string[];
  documentsDemandes?: string[];
  avantages?: string[];
  avantagesEnvironnement?: string[];
  competencesRequises: string[];
  competencesAppreciees: string[];
  softSkills: string[];
  outilsLogiciels: string[];
  formation: string;
  experienceRequise: string;
  languesRequises: string[];
  etapesRecrutement?: string[];
  recruiterContact?: RecruiterContact;
  entrepriseDetails?: EnterpriseDetails;
}

export interface Opportunity {
  id: string;
  companyId: string;
  companyName: string;
  title: string; // e.g., "Conseiller Clientèle Patrimoniale"
  contractType: 'Apprentissage' | 'Professionnalisation' | 'Stage' | 'CDI' | 'CDD' | 'Autre';
  duration: string; // e.g., "12 mois"
  location: string; // e.g., "Commentry", "Clermont-Ferrand"
  status: OpportunityStatus;
  salary?: string; // e.g., "1400€/mois"
  startDate?: string;
  deadline?: string;
  url?: string;
  notes: string;
  privateNotes?: string;
  workflowStep?: number; // 1 to 9
  workflowHistory?: WorkflowStepItem[];
  recruiterContact?: RecruiterContact;
  createdAt: string;
  updatedAt: string;
  aiExtracted: boolean;
  extractedInfo?: ExtractedJobInfo;
}

export type ContactCategory = 'recruiter' | 'alumni' | 'student' | 'sector_pro' | 'other_pro' | 'other';

export interface Contact {
  id: string;
  fullName: string;
  firstName: string;
  lastName: string;
  companyId: string;
  companyName: string;
  jobTitle: string;
  normalizedJobTitle: string; // Normalized by Gemini
  category: ContactCategory;
  relevanceScore: number; // 0 to 100
  connectionPoints: string[]; // e.g., ["Même établissement : IUT Clermont Auvergne"]
  academicPath?: string;
  previousCompanies: string[];
  notes: string;
  linkedInUrl?: string;
  email?: string;
  phone?: string;
  aiCustomMessage?: string; // Personalized outreach message generated by Gemini
  createdAt: string;
}

export interface Company {
  id: string;
  name: string;
  logoUrl?: string;
  sector?: string;
  website?: string;
  notes: string;
  createdAt: string;
  // Summary counts calculated reactively or aggregated
  opportunityCount: number;
  contactCount: number;
  noteCount: number;
}

export interface CalendarEvent {
  id: string;
  title: string;
  date: string; // YYYY-MM-DD
  time?: string; // HH:MM
  type: 'interview' | 'deadline' | 'follow_up' | 'other';
  opportunityId?: string;
  opportunityTitle?: string;
  companyName?: string;
  notes: string;
  completed: boolean;
  createdAt: string;
}

export interface DocumentFile {
  id: string;
  title: string;
  type: 'CV' | 'Lettre de Motivation' | 'Autre';
  content: string; // text content for Gemini indexing
  fileName: string;
  uploadedAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: string;
}

export interface ChatSession {
  id: string;
  personaId: string; // 'general' | 'interview' | 'cv_letter' | 'networking' | 'negotiation'
  personaName: string;
  title: string;
  messages: ChatMessage[];
  updatedAt: string;
}

export interface ToastState {
  isOpen: boolean;
  message: string;
  type: "success" | "error" | "info" | "ai";
}
